# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0b7641a2209bccee82e09346503587f3727016d7754c7dfc4e05fdd0e99c1060b8480533dc91b94cec6d2640a428b232b72e86c6719d00469b1c20735973fb0

test:
  secret_key_base: 6217e3b2166e6a74e60570493ad0e2f340e54680ff34286bae101821fa8e77c73d58bb85b5d5307a6506e96e413fcc579a4c469c6e6c4830cc44caf454158760

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
